package locals

// Ports
var (
	TCP_TRANSECTION_START_PORT int = 9996
	WS_COMMANDER_LISTEN_PORT int = 9997
	UDP_HANDSHAKE_LISTEN_PORT int = 9998
	WS_HANDSHAKE_LISTEN_PORT int = 10000
	WS_SEND_RECEIVE_LISTEN_PORT int = 10001
	WS_MESSAGE_LISTEN_PORT int = 10002
)

// End points
const (
	WS_COMMANDER_END_POINT string = "/cmd"
	WS_MESSAGE_END_POINT string = "/msg"
	WS_SENDRECEIVE_END_POINT string = "/sr"
)

// Others
const (
	ACTIVE_TRANSACTION_LIMIT int = 25
)
